
import java.sql.Array;
import java.util.ArrayList;
import java.util.Vector;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Jun 18, 2020, 11:37:05 PM
 */

/**
 *
 * @author user
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    private void Savethisstate() {

        CurrentState.add(label0.getText());
CurrentState.add(label1.getText());
CurrentState.add(label2.getText());
CurrentState.add(label3.getText());
CurrentState.add(label4.getText());
CurrentState.add(label5.getText());
CurrentState.add(label6.getText());
CurrentState.add(label7.getText());
CurrentState.add(label8.getText());

States.add(new ArrayList<String>(CurrentState));
System.out.print(CurrentState);
System.out.print(States);

CurrentState.removeAll(CurrentState);

    }

    private void ShowPreviousStatesbuttons() {
        if(MovesCount==1) state1.setVisible(true);
if(MovesCount==2)state2.setVisible(true);
if(MovesCount==3)state3.setVisible(true);
if(MovesCount==4)state4.setVisible(true);
if(MovesCount==5)state5.setVisible(true);
if(MovesCount==6)state6.setVisible(true);
if(MovesCount==7)state7.setVisible(true);
if(MovesCount==8)state8.setVisible(true);
if(MovesCount==9)state9.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label0 = new javax.swing.JLabel();
        label0copy = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label1copy = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        label2copy = new javax.swing.JLabel();
        label3copy = new javax.swing.JLabel();
        label4copy = new javax.swing.JLabel();
        label5copy = new javax.swing.JLabel();
        label6copy = new javax.swing.JLabel();
        label7copy = new javax.swing.JLabel();
        label8copy = new javax.swing.JLabel();
        Board = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        state1 = new javax.swing.JLabel();
        state2 = new javax.swing.JLabel();
        state3 = new javax.swing.JLabel();
        state4 = new javax.swing.JLabel();
        state5 = new javax.swing.JLabel();
        state6 = new javax.swing.JLabel();
        state7 = new javax.swing.JLabel();
        state8 = new javax.swing.JLabel();
        state9 = new javax.swing.JLabel();
        start = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setBounds(new java.awt.Rectangle(500, 200, 100, 100));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label0.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        label0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label0.setAlignmentY(0.4F);
        label0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label0MouseClicked(evt);
            }
        });
        getContentPane().add(label0, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 30, 50));

        label0copy.setFont(new java.awt.Font("Arial", 0, 36));
        label0copy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label0copy.setAlignmentY(0.4F);
        label0copy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label0copyMouseClicked(evt);
            }
        });
        getContentPane().add(label0copy, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 30, 50));

        label1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setAlignmentY(0.4F);
        label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label1MouseClicked(evt);
            }
        });
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 30, 50));

        label1copy.setFont(new java.awt.Font("Arial", 0, 36));
        label1copy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1copy.setAlignmentY(0.4F);
        label1copy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label1copyMouseClicked(evt);
            }
        });
        getContentPane().add(label1copy, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 30, 50));

        label2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setAlignmentY(0.4F);
        label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label2MouseClicked(evt);
            }
        });
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 40, 50));

        label3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setAlignmentY(0.4F);
        label3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label3MouseClicked(evt);
            }
        });
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 30, 40));

        label4.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4.setAlignmentY(0.4F);
        label4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label4MouseClicked(evt);
            }
        });
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 30, 40));

        label5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label5.setAlignmentY(0.4F);
        label5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label5MouseClicked(evt);
            }
        });
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 40, 40));

        label6.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        label6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label6.setAlignmentY(0.4F);
        label6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label6MouseClicked(evt);
            }
        });
        getContentPane().add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 30, 40));

        label7.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        label7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label7.setAlignmentY(0.4F);
        label7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label7MouseClicked(evt);
            }
        });
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 30, 40));

        label8.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        label8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label8.setAlignmentY(0.4F);
        label8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label8MouseClicked(evt);
            }
        });
        getContentPane().add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 40, 40));

        label2copy.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        label2copy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2copy.setAlignmentY(0.4F);
        label2copy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label2copyMouseClicked(evt);
            }
        });
        getContentPane().add(label2copy, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 40, 50));

        label3copy.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        label3copy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3copy.setAlignmentY(0.4F);
        label3copy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label3copyMouseClicked(evt);
            }
        });
        getContentPane().add(label3copy, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 30, 40));

        label4copy.setFont(new java.awt.Font("Arial", 0, 36));
        label4copy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4copy.setAlignmentY(0.4F);
        label4copy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label4copyMouseClicked(evt);
            }
        });
        getContentPane().add(label4copy, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 30, 40));

        label5copy.setFont(new java.awt.Font("Arial", 0, 36));
        label5copy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label5copy.setAlignmentY(0.4F);
        label5copy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label5copyMouseClicked(evt);
            }
        });
        getContentPane().add(label5copy, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 40, 40));

        label6copy.setFont(new java.awt.Font("Arial", 0, 36));
        label6copy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label6copy.setAlignmentY(0.4F);
        label6copy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label6copyMouseClicked(evt);
            }
        });
        getContentPane().add(label6copy, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 30, 40));

        label7copy.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        label7copy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label7copy.setAlignmentY(0.4F);
        label7copy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label7copyMouseClicked(evt);
            }
        });
        getContentPane().add(label7copy, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 30, 40));

        label8copy.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        label8copy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label8copy.setAlignmentY(0.4F);
        label8copy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label8copyMouseClicked(evt);
            }
        });
        getContentPane().add(label8copy, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 40, 40));

        Board.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tic-Tac-Toe trans.png"))); // NOI18N
        getContentPane().add(Board, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Next Player:");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("X");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 20, 20));

        state1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bu1k.png"))); // NOI18N
        state1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                state1MouseClicked(evt);
            }
        });
        getContentPane().add(state1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 160, 60));
        state1.setVisible(false);

        state2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bu2.png"))); // NOI18N
        state2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                state2MouseClicked(evt);
            }
        });
        getContentPane().add(state2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, 70));
        state2.setVisible(false);

        state3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bu3.png"))); // NOI18N
        state3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                state3MouseClicked(evt);
            }
        });
        getContentPane().add(state3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));
        state3.setVisible(false);

        state4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bu4.png"))); // NOI18N
        state4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                state4MouseClicked(evt);
            }
        });
        getContentPane().add(state4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, -1));
        state4.setVisible(false);

        state5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bu5.png"))); // NOI18N
        state5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                state5MouseClicked(evt);
            }
        });
        getContentPane().add(state5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));
        state5.setVisible(false);

        state6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bu6.png"))); // NOI18N
        state6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                state6MouseClicked(evt);
            }
        });
        getContentPane().add(state6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, -1, -1));
        state6.setVisible(false);

        state7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bu7.png"))); // NOI18N
        state7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                state7MouseClicked(evt);
            }
        });
        getContentPane().add(state7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));
        state7.setVisible(false);

        state8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bu8.png"))); // NOI18N
        state8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                state8MouseClicked(evt);
            }
        });
        getContentPane().add(state8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, -1, -1));
        state8.setVisible(false);

        state9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bu9.png"))); // NOI18N
        state9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                state9MouseClicked(evt);
            }
        });
        getContentPane().add(state9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, -1, -1));
        state9.setVisible(false);

        start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startMouseClicked(evt);
            }
        });
        getContentPane().add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 380, 50, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gameborder_4.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-140, 80, 1020, 560));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgroundwithtitle_1.jpg"))); // NOI18N
        Background.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Background.setMinimumSize(new java.awt.Dimension(1916, 1062));
        Background.setPreferredSize(new java.awt.Dimension(1500, 700));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1916, 1062));

        pack();
    }// </editor-fold>//GEN-END:initComponents
String dummy;
   public  String change(String a) {
         if(a.equals("O")){dummy="X";}
         else { dummy="O";}
         return dummy ;
    }

    String CurrentPlayer="X";
    String NextPlayer="X";
    int MovesCount=0;
    ArrayList<ArrayList<String>> States=new ArrayList<ArrayList<String>>(81);
    ArrayList<String> CurrentState=new ArrayList<String>(9);
    int ButtonClicked=0;

    private void integrate() {
try{if(ButtonClicked!=0){
    while(States.size()>ButtonClicked){States.remove(States.size()-1);}
}}
catch(IndexOutOfBoundsException e){}




    }

    private void AfterAButtonClickedEvents(){


    if(ButtonClicked!=0){MovesCount=ButtonClicked;}
switch(ButtonClicked){
    case 1:
state2.setVisible(false);
state3.setVisible(false);
state4.setVisible(false);
state5.setVisible(false);
state6.setVisible(false);
state7.setVisible(false);
state8.setVisible(false);
state9.setVisible(false);
break;
case 2:
state3.setVisible(false);
state4.setVisible(false);
state5.setVisible(false);
state6.setVisible(false);
state7.setVisible(false);
state8.setVisible(false);
state9.setVisible(false);
break;
case 3:
state4.setVisible(false);
state5.setVisible(false);
state6.setVisible(false);
state7.setVisible(false);
state8.setVisible(false);
state9.setVisible(false);
break;
case 4:
state5.setVisible(false);
state6.setVisible(false);
state7.setVisible(false);
state8.setVisible(false);
state9.setVisible(false);
break;
case 5:

state7.setVisible(false);
state8.setVisible(false);
state9.setVisible(false);
break;
case 6:
state7.setVisible(false);
state8.setVisible(false);
state9.setVisible(false);
break;
case 7:
state8.setVisible(false);
state9.setVisible(false);
break;
case 8:
state9.setVisible(false);
break;
};






    }




   private void VictoryCheck(){
   String a0=label0.getText();
String a1=label1.getText();
String a2=label2.getText();
String a3=label3.getText();
String a4=label4.getText();
String a5=label5.getText();
String a6=label6.getText();
String a7=label7.getText();
String a8=label8.getText();

   if((a0.equals(a1)&& a1.equals(a2))||(a0.equals(a3)&& a3.equals(a6)) ||(a0.equals(a4)&& a4.equals(a8)) ||(a6.equals(a4)&& a4.equals(a2)) ||(a3.equals(a4)&& a4.equals(a5)) ||(a6.equals(a7)&& a7.equals(a8)) ||(a1.equals(a4)&& a4.equals(a7)) ||(a2.equals(a5)&& a5.equals(a8))){

       if((a0.equals(a1)&& a1.equals(a2)&& (a2.isEmpty()==false))||(a0.equals(a3)&& a3.equals(a6)&& (a6.isEmpty()==false)) ||(a0.equals(a4)&& a4.equals(a8)&& (a8.isEmpty()==false)) ||(a6.equals(a4)&& a4.equals(a2)&& (a2.isEmpty()==false)) ||(a3.equals(a4)&& a4.equals(a5)&& (a5.isEmpty()==false)) ||(a6.equals(a7)&& a7.equals(a8)&& (a8.isEmpty()==false)) ||(a1.equals(a4)&& a4.equals(a7)&& (a7.isEmpty()==false)) ||(a2.equals(a5)&& a5.equals(a8)&& (a8.isEmpty()==false))){
       label0.setVisible(false);label0copy.setText(label0.getText());label0copy.setVisible(true);
label1.setVisible(false);label1copy.setText(label1.getText());  label1copy.setVisible(true);
label2.setVisible(false);label2copy.setText(label2.getText());label2copy.setVisible(true);
label3.setVisible(false);label3copy.setText(label3.getText());label3copy.setVisible(true);
label4.setVisible(false);label4copy.setText(label4.getText());label4copy.setVisible(true);
label5.setVisible(false);label5copy.setText(label5.getText());label5copy.setVisible(true);
label6.setVisible(false);label6copy.setText(label6.getText());label6copy.setVisible(true);
label7.setVisible(false);label7copy.setText(label7.getText());label7copy.setVisible(true);
label8.setVisible(false);label8copy.setText(label8.getText());label8copy.setVisible(true);
   
jLabel2.setText("    Winner:");
String cp=NextPlayer;
jLabel3.setText(change(cp));

       }


   }

   }


    private void label0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label0MouseClicked
label0.setText(NextPlayer);
label0copy.setText(label0.getText());
label0.setVisible(false); /* making ineditable*/
label0copy.setVisible(true);
MovesCount+=1;
NextPlayer=change(NextPlayer);
jLabel3.setText(NextPlayer);

AfterAButtonClickedEvents();
integrate();
Savethisstate();
ShowPreviousStatesbuttons();
ButtonClicked=0;
VictoryCheck();
        // TODO add your handling code here:
}//GEN-LAST:event_label0MouseClicked

    private void label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1MouseClicked
label1.setText(NextPlayer);
label1copy.setText(label1.getText());
label1.setVisible(false);
label1copy.setVisible(true);
MovesCount+=1;
NextPlayer=change(NextPlayer);
jLabel3.setText(NextPlayer);

AfterAButtonClickedEvents();
integrate();
ButtonClicked=0;
Savethisstate();
ShowPreviousStatesbuttons();
VictoryCheck();
        // TODO replace with changeping function
    }//GEN-LAST:event_label1MouseClicked

    private void label2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2MouseClicked

label2.setText(NextPlayer);
label2copy.setText(label2.getText());
label2.setVisible(false);
label2copy.setVisible(true);
MovesCount+=1;
NextPlayer=change(NextPlayer);
jLabel3.setText(NextPlayer);

AfterAButtonClickedEvents();
integrate();
ButtonClicked=0;
Savethisstate();
ShowPreviousStatesbuttons();
VictoryCheck();
      // TODO add your handling code here:
    }//GEN-LAST:event_label2MouseClicked

    private void label3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label3MouseClicked
   label3.setText(NextPlayer);
   label3copy.setText(label3.getText());
label3.setVisible(false);
label3copy.setVisible(true);
   MovesCount+=1;
   NextPlayer=change(NextPlayer);
jLabel3.setText(NextPlayer);

AfterAButtonClickedEvents();
integrate();
ButtonClicked=0;
Savethisstate();
ShowPreviousStatesbuttons();
VictoryCheck();
        // TODO add your handling code here:
    }//GEN-LAST:event_label3MouseClicked

    private void label4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label4MouseClicked
       label4.setText(NextPlayer);
       label4copy.setText(label4.getText());
       label4copy.setVisible(true);
label4.setVisible(false);
MovesCount+=1;
       NextPlayer=change(NextPlayer);
jLabel3.setText(NextPlayer);

AfterAButtonClickedEvents();
integrate();
ButtonClicked=0;
Savethisstate();
ShowPreviousStatesbuttons();
VictoryCheck();
        // TODO add your handling code here:
    }//GEN-LAST:event_label4MouseClicked

    private void label5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label5MouseClicked
label5.setText(NextPlayer);
label5copy.setText(label5.getText());
label5.setVisible(false);
label5copy.setVisible(true);
MovesCount+=1;
NextPlayer=change(NextPlayer);
jLabel3.setText(NextPlayer);

AfterAButtonClickedEvents();
integrate();
ButtonClicked=0;
Savethisstate();
ShowPreviousStatesbuttons();
VictoryCheck();
        // TODO add your handling code here:
    }//GEN-LAST:event_label5MouseClicked

    private void label6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label6MouseClicked
label6.setText(NextPlayer);
label6copy.setText(label6.getText());
label6.setVisible(false);
label6copy.setVisible(true);
MovesCount+=1;
NextPlayer=change(NextPlayer);
jLabel3.setText(NextPlayer);

AfterAButtonClickedEvents();
integrate();
ButtonClicked=0;
Savethisstate();
ShowPreviousStatesbuttons();
VictoryCheck();
        // TODO add your handling code here:
    }//GEN-LAST:event_label6MouseClicked

    private void label7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label7MouseClicked

   label7.setText(NextPlayer);
   label7copy.setText(label7.getText());
label7.setVisible(false);
label7copy.setVisible(true);
MovesCount+=1;
   NextPlayer=change(NextPlayer);
jLabel3.setText(NextPlayer);

AfterAButtonClickedEvents();
integrate();
ButtonClicked=0;
Savethisstate();

ShowPreviousStatesbuttons();

VictoryCheck();
        // TODO add your handling code here:
    }//GEN-LAST:event_label7MouseClicked

    private void label8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label8MouseClicked

   label8.setText(NextPlayer);
   label8copy.setText(label8.getText());
label8.setVisible(false);
label8copy.setVisible(true);
MovesCount+=1;
   NextPlayer=change(NextPlayer);
jLabel3.setText(NextPlayer);
AfterAButtonClickedEvents();
integrate();
ButtonClicked=0;
Savethisstate();
ShowPreviousStatesbuttons();
VictoryCheck();
        // TODO add your handling code here:
    }//GEN-LAST:event_label8MouseClicked

    private void label0copyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label0copyMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_label0copyMouseClicked

    private void state1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_state1MouseClicked
label0.setText(States.get(0).get(0)+"");
label1.setText(States.get(0).get(1)+"");
label2.setText(States.get(0).get(2)+"");
label3.setText(States.get(0).get(3)+"");
label4.setText(States.get(0).get(4)+"");
label5.setText(States.get(0).get(5)+"");
label6.setText(States.get(0).get(6)+"");
label7.setText(States.get(0).get(7)+"");
label8.setText(States.get(0).get(8)+"");
ButtonClicked=1;
MovesCount=ButtonClicked;
if(ButtonClicked%2==0){NextPlayer="X";}
else{NextPlayer="O";}
jLabel3.setText(NextPlayer);
MakeVacanteditable();
VictoryCheck();
        // TODO add your handling code here:
    }//GEN-LAST:event_state1MouseClicked

    private void startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startMouseClicked
label0.setText("");
label1.setText("");
label2.setText("");
label3.setText("");
label4.setText("");
label5.setText("");
label6.setText("");
label7.setText("");
label8.setText("");
States.clear();
state1.setVisible(false);
state2.setVisible(false);
state3.setVisible(false);
state4.setVisible(false);
state5.setVisible(false);
state6.setVisible(false);
state7.setVisible(false);
state8.setVisible(false);
state9.setVisible(false);
MovesCount=0;
ButtonClicked=0;
NextPlayer="X";
jLabel3.setText("X");
MakeVacanteditable();
        // TODO add your handling code here:
    }//GEN-LAST:event_startMouseClicked

    private void state2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_state2MouseClicked

label0.setText(States.get(1).get(0)+"");
label1.setText(States.get(1).get(1)+"");
label2.setText(States.get(1).get(2)+"");
label3.setText(States.get(1).get(3)+"");
label4.setText(States.get(1).get(4)+"");
label5.setText(States.get(1).get(5)+"");
label6.setText(States.get(1).get(6)+"");
label7.setText(States.get(1).get(7)+"");
label8.setText(States.get(1).get(8)+"");
ButtonClicked=2;
MovesCount=ButtonClicked;
if(ButtonClicked%2==0){NextPlayer="X";}
else{NextPlayer="O";}
jLabel3.setText(NextPlayer);
MakeVacanteditable();
VictoryCheck();
        // TODO add your handling code here:
    }//GEN-LAST:event_state2MouseClicked

    private void state3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_state3MouseClicked

        label0.setText(States.get(2).get(0)+"");
label1.setText(States.get(2).get(1)+"");
label2.setText(States.get(2).get(2)+"");
label3.setText(States.get(2).get(3)+"");
label4.setText(States.get(2).get(4)+"");
label5.setText(States.get(2).get(5)+"");
label6.setText(States.get(2).get(6)+"");
label7.setText(States.get(2).get(7)+"");
label8.setText(States.get(2).get(8)+"");
ButtonClicked=3;
MovesCount=ButtonClicked;
if(ButtonClicked%2==0){NextPlayer="X";}
else{NextPlayer="O";}
jLabel3.setText(NextPlayer);
MakeVacanteditable();
VictoryCheck();
        // TODO add your handling code here:
    }//GEN-LAST:event_state3MouseClicked

    private void state4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_state4MouseClicked
     
        label0.setText(States.get(3).get(0)+"");
label1.setText(States.get(3).get(1)+"");
label2.setText(States.get(3).get(2)+"");
label3.setText(States.get(3).get(3)+"");
label4.setText(States.get(3).get(4)+"");
label5.setText(States.get(3).get(5)+"");
label6.setText(States.get(3).get(6)+"");
label7.setText(States.get(3).get(7)+"");
label8.setText(States.get(3).get(8)+"");
ButtonClicked=4;
MovesCount=ButtonClicked;
if(ButtonClicked%2==0){NextPlayer="X";}
else{NextPlayer="O";}
jLabel3.setText(NextPlayer);
MakeVacanteditable();
VictoryCheck();
        // TODO add your handling code here:
    }//GEN-LAST:event_state4MouseClicked

    private void state5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_state5MouseClicked
     
        label0.setText(States.get(4).get(0)+"");
label1.setText(States.get(4).get(1)+"");
label2.setText(States.get(4).get(2)+"");
label3.setText(States.get(4).get(3)+"");
label4.setText(States.get(4).get(4)+"");
label5.setText(States.get(4).get(5)+"");
label6.setText(States.get(4).get(6)+"");
label7.setText(States.get(4).get(7)+"");
label8.setText(States.get(4).get(8)+"");
ButtonClicked=5;
MovesCount=ButtonClicked;
if(ButtonClicked%2==0){NextPlayer="X";}
else{NextPlayer="O";}
jLabel3.setText(NextPlayer);
MakeVacanteditable();
VictoryCheck();
        // TODO add your handling code here:
    }//GEN-LAST:event_state5MouseClicked

    private void state6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_state6MouseClicked
       label0.setText(States.get(5).get(0)+"");
label1.setText(States.get(5).get(1)+"");
label2.setText(States.get(5).get(2)+"");
label3.setText(States.get(5).get(3)+"");
label4.setText(States.get(5).get(4)+"");
label5.setText(States.get(5).get(5)+"");
label6.setText(States.get(5).get(6)+"");
label7.setText(States.get(5).get(7)+"");
label8.setText(States.get(5).get(8)+"");
ButtonClicked=6;
MovesCount=ButtonClicked;
if(ButtonClicked%2==0){NextPlayer="X";}
else{NextPlayer="O";}
jLabel3.setText(NextPlayer);
MakeVacanteditable();
VictoryCheck();
        // TODO add your handling code here:
    }//GEN-LAST:event_state6MouseClicked

    private void state7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_state7MouseClicked

        label0.setText(States.get(6).get(0)+"");
label1.setText(States.get(6).get(1)+"");
label2.setText(States.get(6).get(2)+"");
label3.setText(States.get(6).get(3)+"");
label4.setText(States.get(6).get(4)+"");
label5.setText(States.get(6).get(5)+"");
label6.setText(States.get(6).get(6)+"");
label7.setText(States.get(6).get(7)+"");
label8.setText(States.get(6).get(8)+"");
ButtonClicked=7;
MovesCount=ButtonClicked;
if(ButtonClicked%2==0){NextPlayer="X";}
else{NextPlayer="O";}
jLabel3.setText(NextPlayer);
MakeVacanteditable();
VictoryCheck();
        // TODO add your handling code here:
    }//GEN-LAST:event_state7MouseClicked

    private void state8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_state8MouseClicked
       label0.setText(States.get(7).get(0)+"");
label1.setText(States.get(7).get(1)+"");
label2.setText(States.get(7).get(2)+"");
label3.setText(States.get(7).get(3)+"");
label4.setText(States.get(7).get(4)+"");
label5.setText(States.get(7).get(5)+"");
label6.setText(States.get(7).get(6)+"");
label7.setText(States.get(7).get(7)+"");
label8.setText(States.get(7).get(8)+"");
ButtonClicked=8;
MovesCount=ButtonClicked;
if(ButtonClicked%2==0){NextPlayer="X";}
else{NextPlayer="O";}
jLabel3.setText(NextPlayer);
MakeVacanteditable();
VictoryCheck();
        // TODO add your handling code here:
    }//GEN-LAST:event_state8MouseClicked

    private void state9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_state9MouseClicked
      label0.setText(States.get(8).get(0)+"");
label1.setText(States.get(8).get(1)+"");
label2.setText(States.get(8).get(2)+"");
label3.setText(States.get(8).get(3)+"");
label4.setText(States.get(8).get(4)+"");
label5.setText(States.get(8).get(5)+"");
label6.setText(States.get(8).get(6)+"");
label7.setText(States.get(8).get(7)+"");
label8.setText(States.get(8).get(8)+"");
ButtonClicked=9;
MovesCount=ButtonClicked;
if(ButtonClicked%2==0){NextPlayer="X";}
else{NextPlayer="O";}
jLabel3.setText(NextPlayer);
MakeVacanteditable();
VictoryCheck();
        // TODO add your handling code here:
    }//GEN-LAST:event_state9MouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved

        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseMoved

    private void label1copyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1copyMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_label1copyMouseClicked

    private void label2copyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2copyMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_label2copyMouseClicked

    private void label3copyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label3copyMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_label3copyMouseClicked

    private void label4copyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label4copyMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_label4copyMouseClicked

    private void label5copyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label5copyMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_label5copyMouseClicked

    private void label6copyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label6copyMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_label6copyMouseClicked

    private void label7copyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label7copyMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_label7copyMouseClicked

    private void label8copyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label8copyMouseClicked
        // TODO add your handling code here:
}//GEN-LAST:event_label8copyMouseClicked

   

   

   

  







    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Board;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel label0;
    private javax.swing.JLabel label0copy;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label1copy;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label2copy;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label3copy;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label4copy;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label5copy;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label6copy;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label7copy;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label8copy;
    private javax.swing.JLabel start;
    private javax.swing.JLabel state1;
    private javax.swing.JLabel state2;
    private javax.swing.JLabel state3;
    private javax.swing.JLabel state4;
    private javax.swing.JLabel state5;
    private javax.swing.JLabel state6;
    private javax.swing.JLabel state7;
    private javax.swing.JLabel state8;
    private javax.swing.JLabel state9;
    // End of variables declaration//GEN-END:variables

    private void MakeVacanteditable() {/*Ofcourse,this is for edits before reaching Winner*/
        if(label0.getText().equals("")){label0.setVisible(true); label0copy.setVisible(false);}
        if(label1.getText().equals("")){label1.setVisible(true); label1copy.setVisible(false);}
if(label2.getText().equals("")){label2.setVisible(true);label2copy.setVisible(false);}
if(label3.getText().equals("")){label3.setVisible(true);label3copy.setVisible(false);}
if(label4.getText().equals("")){label4.setVisible(true);label4copy.setVisible(false);}
if(label5.getText().equals("")){label5.setVisible(true);label5copy.setVisible(false);}
if(label6.getText().equals("")){label6.setVisible(true);label6copy.setVisible(false);}
if(label7.getText().equals("")){label7.setVisible(true);label7copy.setVisible(false);}
if(label8.getText().equals("")){label8.setVisible(true);label8copy.setVisible(false);}

label1copy.setText(label1.getText());
label2copy.setText(label2.getText());
label3copy.setText(label3.getText());
label4copy.setText(label4.getText());
label5copy.setText(label5.getText());
label6copy.setText(label6.getText());
label7copy.setText(label7.getText());
label8copy.setText(label8.getText());
 
jLabel2.setText("Next Player:");
    }


    


}
